config/routes.rb
Mylomba::Application.routes.draw do
  get "controls/index"
  resources :controls
  devise_for :users
  
  root :to => 'controls#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/control.rb
class Control < ActiveRecord::Base
  attr_accessible :activity_date, :berhasil, :category, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :control
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
    	before_filter :authenticate_user!, :except => [:index]
  def index
  	@control = Control.all
  end

  def new
  	@control = Control.new
  	@user = User.all 
  end

  def create
	@control = Control.new(params[:control][:berhasil])
	if @control.save
		flash[:notice] = "Create new Article Successfully"
		redirect_to :action => :index
	else
		render :action => :new
	end  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Lomba</title>
</head>
<body>
<div id="tbl">
<h3>Control Lomba</h3>
<div style="margin-left:80%;margin-right:17%;" class="button"><%=link_to "Input", new_control_path %></div>
	<div id="tablewrapper">
		<div id="tableheader">
   	  `<div class="search">
          <select id="columns" onchange="sorter.search('query')"></select>
          <input type="text" id="query" onkeyup="sorter.search('query')" />
            </div>
        <span class="details">
				<div>Records <span id="startrecord"></span>-<span id="endrecord"></span> of <span id="totalrecords"></span></div>
        		<div><a href="javascript:sorter.reset()">reset</a></div>
        	</span>
        </div>
<table cellpadding="0" cellspacing="0" border="0" id="table" class="tinytable">
 <thead>
	<tr>
		<th><h3>No</h3></th>
		<th><h3>Tanggal</h3></th>
		<th><h3>Nama</h3></th>
		<th><h3>Kategori</h3></th>
		<th><h3>Berhasil</h3></th>
		<th><h3>Keterangan</h3></th>
	</tr>
</thead>
	<tbody>
	<%
	@control.each do |c|
	%>
	<tr>
		<td><%= c.id %></td>
		<td><%= c.activity_date %></td>
		<td><%= c.user_id %></td>
		<td><%= c.category %></td>
		<td><%= c.berhasil %></td>
		<td>6</td>
	</tr>
	<% end %>
</tbody>
</table>
<div id="tablefooter">
          <div id="tablenav">
            	<div>
                    <%= image_tag('first.gif', :title => 'First', :alt => 'First', :width => '16', :height => '16', :onclick => "sorter.move(-1,true)") %>
                    <%= image_tag('previous.gif', :title => 'Previous', :alt => 'Previous', :width => '16', :height => '16', :onclick => "sorter.move(-1)") %>
                    <%= image_tag('next.gif', :title => 'Next', :alt => 'Next', :width => '16', :height => '16', :onclick => "sorter.move(1)") %>
                    <%= image_tag('next.gif', :title => 'Next', :alt => 'Next', :width => '16', :height => '16', :onclick => "sorter.move(1,true)") %>
                </div>
                <div>
                	<select id="pagedropdown"></select>
				</div>
                <div>
                	<a href="javascript:sorter.showall()">view all</a>
                </div>
    </div>
			<div id="tablelocation">
            	<div>
                    <select onchange="sorter.size(this.value)">
                    <option value="5">5</option>
                        <option value="10" selected="selected">10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <span>Entries Per Page</span>
                </div>
                <div class="page">Page <span id="currentpage"></span> of <span id="totalpages"></span></div>
            </div>
      </div>
    </div>
	<script type="text/javascript">
	var sorter = new TINY.table.sorter('sorter','table',{
		headclass:'head',
		ascclass:'asc',
		descclass:'desc',
		evenclass:'evenrow',
		oddclass:'oddrow',
		evenselclass:'evenselected',
		oddselclass:'oddselected',
		paginate:true,
		size:10,
		colddid:'columns',
		currentid:'currentpage',
		totalid:'totalpages',
		startingrecid:'startrecord',
		endingrecid:'endrecord',
		totalrecid:'totalrecords',
		hoverid:'selectedrow',
		pageddid:'pagedropdown',
		navid:'tablenav',
		sortcolumn:1,
		sortdir:1,
		sum:[8],
		avg:[6,7,8,9],
		columns:[{index:7, format:'%', decimals:1},{index:8, format:'$', decimals:0}],
		init:true
	});
  </script>
</body>
</html>

app/views/controls/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Input Lomba</title>
  <%= stylesheet_link_tag "controls", :media => "all" %>
</head>
<body>
	<%= current_user.username %> 
	<%= link_to 'Logout', destroy_user_session_path, :method => :delete %> 
	<%= form_for :control,:url => {:action => :create} do |form| %>
	<table align='center' width='50%' border="1">
		<tr>
			<td>Nama</td>
			<td><%= form.hidden_field('user_id', :value => current_user.id) %>
				<%= current_user.email %></option>
				</td>
		</tr>
		<tr>
			<td>Kategori</td>
			<td><select name='category' class="input">
				<option value="Sholat">Sholat</option>
			</select></td>
		</tr>
		<tr>
			<td>Berhasil</td>
			<td>
			<%= check_box(:berhasil,"",:value=>"asda") %> Shubuh
			</td>
		</tr>
		<tr>
			<td>Tanggal</td>
			<td></td>
		</tr>
		<tr>
			<td colspan="2" align="right"><input type="button" name='kembali' class="button" value="Kembali" />
				<input type="submit" name='Simpan' class="button" />
		</td>
		</tr>
	</table>
	<% end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mylomba</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>